
v cnst[95];
a acnst[131];
v glob1_1;
v glob1_2;
v glob1_3;
v glob1_4;
v glob1_5;
v glob1_6;
v glob1_7;
v glob1_8;
v glob3_1;
v glob3_2;
v glob3_3;
v glob10_1;
v glob10_2;
v glob10_3;
v glob10_4;
v glob15_1;
v glob24_1;
v glob24_2;
v glob24_3;
v glob30_1;
v glob71_1;
extern Void r2 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r3 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r4 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r5 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r6 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r7 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r8 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r9 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r10 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r11 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r12 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r13 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r14 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r15 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r16 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r17 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r18 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r19 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r20 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r21 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r22 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r23 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r24 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r25 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r26 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r27 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r28 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r29 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r30 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r31 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r32 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r33 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r34 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r35 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r36 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r37 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r38 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r39 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r40 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r41 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r42 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r43 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r44 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r45 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r46 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r47 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r48 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r49 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r50 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r51 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r52 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r53 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r54 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r55 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r56 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r57 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r58 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r59 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r60 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r61 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r62 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r63 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r64 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r65 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r66 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r67 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r68 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r69 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r70 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r71 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r72 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r73 PP((long *rez, boolean *success, ptr_ *pl));
