
Procedure USE_11(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_17(p1,p2,p3:a;var rez:a);begin end;

Procedure USE_39(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_49(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_50(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_51(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_52(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_53(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_54(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_55(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_56(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_57(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_58(p1,p2,p3:a;var rez:a);begin end;



Procedure USE_94(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_95(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_96(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_97(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_98(p1,p2,p3:a;var rez:a);begin end;

Procedure USE_99(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_100(p1,p2,p3:a;var rez:a);begin end;

Procedure USE_115(p1,p2,p3:a;var rez:a);begin end;


Procedure USE_123(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_124(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_125(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_126(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_127(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_128(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_129(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_130(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_131(p1,p2,p3:a;var rez:a);begin end;

Procedure USE_133(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_134(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_135(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_136(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_137(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_138(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_139(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_140(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_141(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_142(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_143(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_144(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_145(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_146(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_147(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_148(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_149(p1,p2,p3:a;var rez:a);begin end;
Procedure USE_150(p1,p2,p3:a;var rez:a);begin end;