REM   WI COPY WIN
REM   WI COPY ..
REM   WI DEL
%1 *.CFG       %2
%1 XW.BAT      %2
%1 *.DLL       %2
%1 *.RES       %2
%1 INTWM.EXE   %2
%1 INTDLL.EXE  %2
%1 RIGCWM.EXE  %2
%1 GENCFG.EXE  %2
%1 RWIN.EXE    %2
%1 TPCW.EXE    %2
%1 TPW.TPL     %2
%1 MYTPW.EXE   %2 
%1 EDITWIN.EXE %2
%1 XW1.BAT     %2
%1 PRESS.TXT   %2
%1 STD*.*      %2
%1 *.PIF       %2
%1 MSGBX.TXT   %2
%1 LB*.RIG     %2
%1 RIGDDE.*    %2
%1 *.bmp       %2