
v cnst[69];
a acnst[143];
v glob2_1;
v glob2_2;
v glob2_3;
v glob2_4;
v glob2_5;
v glob2_6;
v glob2_7;
v glob2_8;
v glob1_1;
v glob1_2;
v glob1_3;
v glob1_4;
v glob1_5;
v glob1_6;
v glob24_1;
v glob24_2;
v glob26_1;
v glob3_1;
extern Void r2 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r3 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r4 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r5 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r6 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r7 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r8 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r9 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r10 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r11 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r12 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r13 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r14 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r15 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r16 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r17 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r18 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r19 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r20 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r21 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r22 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r23 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r24 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r25 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r26 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r27 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r28 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r29 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r30 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r31 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r32 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r33 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r34 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r35 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r36 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r37 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r38 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r39 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r40 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r41 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r42 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r43 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r44 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r45 PP((long *rez, boolean *success, ptr_ *pl));
extern Void r46 PP((long *rez, boolean *success, ptr_ *pl));
